### ISSUE TITLE
Add spellchecker.library support

### ISSUE THREAD

**Issue by polluks** [sodero/MUI-Vim#14]
to make Vim more native

**Comment by sodero** [comment]
But there is already spelling support built into Vim. I don't know that library though, is it MorphOS only?

**Comment by polluks** [comment]
Indeed, Vim has two competing spelling systems in MorphOS. This library is a wrapper of hunspell.

**Comment by polluks** [comment]
Indeed, Vim has two competing spelling systems in MorphOS. This library is a wrapper of hunspell.

**Comment by ernsteiswuerfel** [comment]
Yes, would be nice if the native one can be used on MorphOS.

**Comment by sodero** [comment]
I'm reluctant to use this since it's for MorphOS only. Ideally I'd like all Amiga flavours to be supported and to keep the os-specific parts to a minimum. Apart from that, the builtin spelling functionality is excellent and my experience tells me that it's not a good idea to shoehorn functionality into Vim. Doing so would making it more difficult to keep up with upstream. If we would like Vim to be more integrated I'd much rather see Arexx support. It would be quite fancy to be able to write plugins using Arexx, to interact with other applications in a nice way.

**Comment by polluks** [comment]
Full acknowledge!
An Arexx port is more portable than a library, I will take a look...
